### ISSUE TITLE
Question: FreeBSD HP Ultrium 3000 supported?

### ISSUE THREAD

**Issue by roker** [LinearTapeFileSystem/ltfs#225] opened 2020-11-08 08:23 UTC
With a tad of pain (you are having duplicate symbols on v2.4-stable, Makefile uses libtape_cam_la-ibm_tape.o twice, first as .libs/libtape_cam_la-ibm_tape.o and second time as ./.libs/libtape_cam_la-ibm_tape.o) I have compiled latest sources which should have patch for non IBM tapes. 

I have checked hp_tape.c and found this, which looked very promising:
`struct supported_device *hp_supported_drives[] = {
                TAPEDRIVE( HP_VENDOR_ID,  "Ultrium 5-SCSI",  DRIVE_LTO5,    "[Ultrium 5-SCSI]" ),  /* HP Ultrium Gen 5  */`

But running ltfs produces:

`18db0 LTFS31223I Opening a device through CAM driver (/dev/sa0)

18db0 LTFS31228I Product ID is 'Ultrium 5-SCSI'

18db0 LTFS31229I Vendor ID is HP

18db0 LTFS31230I Unsupported Drive 'Ultrium 5-SCSI  Z64D'

18db0 LTFS12012E Cannot open device: failed backend open call.

18db0 LTFS10004E Cannot open device '/dev/sa0'.`

Is there something wrong with the way I build the code, hp ultrium not supported or something else? If this is a bug, I can help you with debugging...

**Comment by roker** [comment] 2020-11-08 09:27
Ok, now I understand. LTFS has support for other vendors and tapes but no one modified the freebsd part of LTFS code to actually use the support.

**Comment by piste-jp-ibm** [comment] 2020-11-10 14:12
Sorry, I don't have a time to make a response in a few days.

Yes, you are right. Actually drive support code is on OS dependent code, called `tape driver`. And now, only `linux-sg` and `osx-iokit` supports HP/Quantum drives. 

HP guys kindly fixed my first trial code and confirmed behavior on their equipment for HP drives on Linux and Mac. And another contributer kindly confirmed the behavior on a Quantum HH drive on Linux. So I added it as `supported`.

Honestly I forget to take care about other OSs (may be the reason is they are not the code I'm not an originator...). 

I can try to port the code to FreeBSD and NetBSD and I can confirm the compile. But I can't have any good physical environment for testing FreeBSD and NetBSD porting. It is very helpful if you can do that.

**Comment by kev009** [comment] 2020-12-02 19:47
@piste-jp-ibm can you fix the duplicate symbol issue in 2.4?  I would like to package it for freebsd with or without the other drive support.

**Comment by piste2750** [comment] 2020-12-04 04:31
@kev009 ,

I fixed and the fix was merged to master already.

**Comment by kev009** [comment] 2020-12-04 04:40
@piste2750 thanks can you point me to the commit I will need to pull that into our ports system in the mean time.

**Comment by piste2750** [comment] 2020-12-04 06:11
@kev009 ,

Are you saying about the commit hash of this change? The change s merged to the `master` branch of this repository. The hash is`be1b873`.

**Comment by piste-jp-ibm** [comment] 2021-01-18 02:23
Sorry, this fix is not merged yet.

**Closed** 2021-01-18 05:14 UTC
Labels: bug
