### ISSUE TITLE
Best HBAs and drives to use with LTFS

### ISSUE THREAD

**Issue by z3cko** [LinearTapeFileSystem/ltfs#442] opened 2024-03-19 13:27 UTC
**Is your feature request related to a problem? Please describe.**

I was using LTFS in the past with mixed results. While ca. 3 years ago everything was working as expected, I cannot use tapes created back then because of read errors. I had a different controller then, but would also definitely buy a suggested controller which works 100%.

**Describe the solution you'd like**

Please, can we have a list of suggested HBAs so we can use LTFS properly? What is everyone here using successfully?

Thanks for any pointer!

**Comment by piste-jp-ibm** [comment] 2024-03-25 01:27
Compatibility verification between drive and HBA is out-of-scope of this project. 

Drive vendors might provide supported HBA lists on their web site. Please use a HBA the vendor recommends or they are saying 'supported'.

I described a few HBAs I confirmed on my bench below, but it is impossible to list all supported HBAs here without any contribution from others on both work time and money.

https://github.com/LinearTapeFileSystem/ltfs/wiki/HBA-info

**Comment by piste-jp-ibm** [comment] 2024-04-17 00:12
@DarrenPIngram ,

Thank you for your suggestion. Where is the best place you think?

I think the repository and Wiki on this project is not good places. What is your suggestion about the place?

**Comment by piste-jp-ibm** [comment] 2024-04-23 05:20
> I am not familiar with the user's use of Wiki here on Github, but could there be scope even for a new "branch" and people could submit PRs to a specific page or pages? I don't know the back-end's granularity for permissions, but I could see you would not want it in the "code's branch".

The Wiki on GH doesn't have any "branch" at all and it doesn't have any function to correspond with an issue like code change. It just holds documents and only project member can modify them. So I think Wiki is not a good place, because one of the members need to modify anyway.

The point is how to maintain the list. I'm not sure it is really valuable for this project. The main statement is "Please use a HBA the vendor recommends or they are saying 'supported'.". We don't want to recommend any 3rd-party HBAs that is not supported by the tape drive vendors...

**Comment by piste-jp-ibm** [comment] 2024-04-23 06:34
Thank you for your quick response.

How about this.

1. Create a page on the Wiki on this project
2. The page has a description like "Official HBA support information is provided from each vendor. Please use the HBA listed in the official support list provided from each tape drive vendor. The list here is unofficial list that LTFS users confirms they are working on their environment. The LTFS project never provides any guarantee."
3. Create a issue template for providing HBA data
4. Anyone can open an issue for providing HBA data
5. Project member update the page on the Wiki based on the issue and close it after updating the page

**Comment by piste-jp-ibm** [comment] 2024-04-23 06:45
OK. Start from that for now.

Let's see what will happen.

**Comment by piste-jp-ibm** [comment] 2024-05-17 06:43
I prepared the page on Wiki and the report template on the repository.

See https://github.com/LinearTapeFileSystem/ltfs/wiki/Confirmed-HBA-list.

**Comment by piste-jp** [comment] 2024-06-21 06:35
Close this because there is no activity long time.

Please feel free to reopen if something new is found.

**Closed by piste-jp** 2024-06-21 06:35 UTC
Labels: question
